/*
* Nach dem Beispiel https://github.com/peter-ha/qskinny/tree/iot-dashboard/examples/iotdashboard
*/
import { StyleMetrics } from "std-widgets.slint";

struct Palette  {
    menuBar : brush,
    mainContent : brush,
    box : brush,
    lightDisplay : brush,
    pieChart : brush,
    roundButton : brush,
    segmentedBox : brush,
    text : brush,
    shadow : brush,
}

global Skin  {
    in property<bool> day: !StyleMetrics.dark-color-scheme;
    out property<Palette> palette : root.day ? {
    menuBar : #6D7BFB,
    mainContent :  #fbfbfb,
    box :   #ffffff,
    lightDisplay : #ffffff,
    pieChart : #ffffff,
    roundButton : #f7f7f7,
    segmentedBox : #f4f4f4,
    text : #000,
    shadow : #0001,
    } : {
    menuBar : #2937A7,
    mainContent : #040404,
    box : #000000,
    lightDisplay : #000000,
    pieChart : #000000,
    roundButton : #0a0a0a,
    segmentedBox : #0c0c0c,
    text : #fff,
    shadow : #fff1,
    };

    // From Skin::initHints in Skin.cpp
    out property <length> DefaultFont: 12px;
    out property <length> TinyFont: 9px;
    out property <length> SmallFont: 10px;
    out property <length> MediumFont: 13px;
    out property <length> LargeFont: 20px;
    out property <length> HugeFont: 27px; // (also, bold)
    out property <length> TitleFont: 10px; // (also, bold)
}

component BoxBase inherits Rectangle {
    background: Skin.palette.box;
    drop-shadow-offset-x: 6px;
    drop-shadow-offset-y: 6px;
    drop-shadow-blur: 6px;
    drop-shadow-color: Skin.palette.shadow;
}

component Box inherits BoxBase {
    in property <string> title;
    VerticalLayout {
        if(root.title != "") : Text {
            text <=> root.title;
            font-size: Skin.TitleFont;
            font-weight: 700;
        }
        spacing: 0px;
        padding: 3px;
        @children
    }
}

component TitleValueBox inherits VerticalLayout {
    spacing: 8px;
    horizontal-stretch: 100;
}

component ValueLabel inherits Text {
    in property <string> value <=> root.text;
    font-size: Skin.HugeFont;
    font-weight: 700;
    color: #929cb2;
}

component RoundedIcon inherits Rectangle {
    in property <brush> gradient-box;
    in property <image> iconName <=> m-graphicLabel.source;
    in property <float> background-opacity <=> background-fill.opacity;
    height: 40px;
    width: 40px;

    background-fill := Rectangle {
        background: root.gradient-box;
        border-radius: 6px;
        opacity: 1.0;
    }
    m-graphicLabel := Image {
        x: (parent.width - self.width) / 2;
        y: (parent.height - self.height) / 2;
    }
}

component BoxedWidget inherits Box {
    callback clicked <=> ta.clicked;
    in property <image> iconFile <=> icon.iconName;
    in-out property <string> value <=> val.value;
    in property <brush> gradient-box <=> icon.gradient-box;
    in property <string> title- <=> titleLabel.text;
    ta := TouchArea {
        HorizontalLayout {
            spacing: 12px;
            icon := RoundedIcon {}
            TitleValueBox {
                titleLabel := Text {
                    font-size: Skin.TitleFont;
                    font-weight: 700;
                }
                val := ValueLabel {}
            }
        }
    }
}

component Temperatur inherits BoxedWidget {
    in-out property <string> temperature;
    title-: "Temperatur";
    iconFile: @image-url("../images/temperature.png");
    value: (root.temperature < 0 ? "-" : "") + root.temperature + "°C";
    gradient-box: @linear-gradient(180deg, #ff7d34, #ff3122);
    clicked() => {//TODO
    }
}

component Luftfeuchtigkeit inherits BoxedWidget {
    in-out property <string> humidity;
    title-: "Luftfeuchtigkeit";
    iconFile: @image-url("../images/humidity.png");
    value: root.humidity + "%";
    gradient-box: @linear-gradient(180deg, #6776FF, #6100FF);
    clicked() => {//TODO
    }
}

component Luftdruck inherits BoxedWidget {
    in-out property <string> pressure;
    title-: "Luftdruck";
    iconFile: @image-url("../images/pressure.png");
    value: root.pressure + "hPa";
    gradient-box: @linear-gradient(180deg, #FFCE50, #f99055);
    clicked() => {//TODO
    }
}

component MainContent inherits VerticalLayout {
    in property <string> temperature;
    in property <string> humidity;
    in property <string> pressure;

    in property <int> temperature_progress;
    in property <int> humidity_progress;
    in property <int> pressure_progress;

    in property <string> time;

    in property <[int]> temperature_values;
    in property <[int]> humidity_values;
    in property <[int]> pressure_values;

    in property <bool> show_temperature;
    in property <bool> show_humidity;
    in property <bool> show_pressure;
    
    GridLayout {
        spacing: 6px;
        padding-top: 0px;
        padding-bottom: 0px;
        Temperatur {
            row: 0; col: 0;
            temperature: root.temperature;
        }
        Luftfeuchtigkeit {
            row: 0; col: 1;
            humidity: root.humidity;
        }
        Luftdruck {
            row: 1; col: 0;
            pressure: root.pressure;
        }
    }
}

export component MainWindow inherits Window {
    in property <string> temperature : "23,6"; //°C
    in property <string> humidity : "32"; //%
    in property <string> pressure : "1034"; //hPa
    in property <string> co2 : "500"; //ppm
    in property <string> tvoc : "0"; //ppb

    in property <int> temperature_progress : 58;
    in property <int> humidity_progress : 32;
    in property <int> pressure_progress : 90;

    in property <string> time : "23:06.02";

    in property <[int]> temperature_values : [30, 15, 30, 40, 60, 10, 70, 20, 40];
    in property <[int]> humidity_values : [40, 55, 60, 50, 40, 50, 75, 80, 100];
    in property <[int]> pressure_values : [60, 45, 60, 70, 10, 70, 20, 50, 20];

    title: "Wetterstation";
    MainContent {
        temperature: root.temperature;
        humidity: root.humidity;
        pressure: root.pressure;

        temperature_progress: root.temperature_progress;
        humidity_progress: root.humidity_progress;
        pressure_progress: root.pressure_progress;

        time: root.time;

        temperature_values: root.temperature_values;
        humidity_values: root.humidity_values;
        pressure_values: root.pressure_values;
    }
}
