/*
import { Button, VerticalBox , AboutSlint } from "std-widgets.slint";


export component AppWindow inherits Window {
    width: 320px;
    height: 240px;
    in-out property<int> counter: 42;
    callback request-increase-value();

    default-font-size: 32px;

    VerticalBox { 
        Text {
            text: "Counter: \{root.counter}";
        }
        Button {
            text: "Increase value";
            clicked => { 
                root.request-increase-value();
            }
        }
     }
}
*/
import { AboutSlint, Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window{
    width: 320px;
    height: 240px;
    in-out property <int> humidity: 42;
    callback request-increase-value();
    VerticalBox {
        alignment: start;
        Text {
            text: "Humi: \{root.humidity}%";
            font-size: 36px;
            horizontal-alignment: center;
        }
        TouchArea {
            AboutSlint {
                preferred-height: 150px;
            }
            clicked => {root.request-increase-value();}
        }
    }
}