// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

export global Images {
    //TODO Temperatur, Luftfeuchtigkeit, Luftdruck Bilder hier einfügen
    in property <image> arrow-left: @image-url("assets/arrow-left.svg");
    in property <image> arrow-right: @image-url("assets/arrow-right.svg");
    in property <image> check: @image-url("assets/check.svg");
    in property <image> sunny: @image-url("assets/sunny.svg");
    in property <image> cloud: @image-url("assets/cloud.svg");
    in property <image> cloudy: @image-url("assets/cloudy.svg");
    in property <image> foggy: @image-url("assets/foggy.svg");
    in property <image> rainy1: @image-url("assets/rainy1.svg");
    in property <image> settings: @image-url("assets/settings.svg");
    in property <image> information: @image-url("assets/information.svg");
    in property <image> spyrosoft-logo: @image-url("assets/spyrosoft-logo.svg");
}