// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { Theme } from "theme.slint";
import { Navigation, MenuButton, Menu, Value } from "widgets/widgets.slint";
import { Balance, Overview, Usage, UsageAdapter, Weather, MenuPage, MenuOverviewAdapter, About , Dashboard} from "pages/pages.slint";
import { Time } from "pages/time.slint";

export component SmallMain {
    i-navigation := Navigation {
        pagination-clicked => {
            i-menu.open-menu();
            i-navigation.hide();
        }

        clicked => {
            i-menu.hide-button();
        }

        current-index <=> MenuOverviewAdapter.current-page;
        page-count: MenuOverviewAdapter.count;

        if(i-navigation.current-index <= 1 && !i-menu.open) : Overview {
            index: 0;
            current-index: i-navigation.current-index;
        }
        if(i-navigation.current-index >= 0 && i-navigation.current-index <= 2 && !i-menu.open) : Weather {
            index: 1;
            current-index: i-navigation.current-index;
        }
        if(i-navigation.current-index >= 1 && i-navigation.current-index <= 3 && !i-menu.open) : Time {
            index: 2;
            current-index: i-navigation.current-index;
        }
    }

    i-menu := Menu {
        preferred-width: 100%;
        preferred-height: 100%;
        start-y:  25px;
        end-y: 22px;
        menu-width: parent.width - 8px;
        menu-height: parent.height - 14px;

        if(i-menu.open) : MenuPage {
            page-changed => {
                i-menu.hide();
            }

            close => {
                i-menu.hide();
            }

            preferred-width: 100%;
            preferred-height: 100%;
        }
    }
}
