// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { Page } from "page.slint";
import { GroupBox, ValueDisplay, Value } from "../widgets/widgets.slint";

export global OverviewAdapter {
    in property <string> temperature-title: "Temperatur";
    in property <string> humidity-title: "Luftfeuchtigkeit";
    in property <string> pressure-title: "Luftdruck";
    in property <[Value]> temperature-model: [
        {
            title: "Innen",
            value: 21.2,
            unit: "°C",
        },
        {
            title: "Aussen",
            value: 9.2,
            unit: "°C",
        }
    ];
    in property <[Value]> humidity-model: [
        {
            title: "Innen",
            value: 54,
            unit: "%",
        },
        {
            title: "Aussen",
            value: 10,
            unit: "%",
        }
    ];
    in property <[Value]> pressure-model: [
        {
            title: "Innen",
            value: 1013,
            unit: "hPa",
        }
    ];
}

export component Overview inherits Page {
    in property <string> temperature-title <=> OverviewAdapter.temperature-title;
    in property <string> humidity-title <=>  OverviewAdapter.humidity-title;
    in property <string> pressure-title <=>  OverviewAdapter.pressure-title;
    in property <[Value]> temperature-model <=> OverviewAdapter.temperature-model;
    in property <[Value]> humidity-model <=> OverviewAdapter.humidity-model;
    in property <[Value]> pressure-model <=> OverviewAdapter.pressure-model;

    width: 100%;
    height: 100%;

    VerticalLayout {
        spacing: 3px;

        i-temperature-group := GroupBox {
            title: root.temperature-title;

            ValueDisplay {
                active: root.active;
                model: root.temperature-model;
            }
        }

        i-humidity-group := GroupBox {
            title: root.humidity-title;

            ValueDisplay {
                active: root.active;
                alternative-colors: true;

                model: root.humidity-model;
            }
        }

        i-pressure-group := GroupBox {
            title: root.pressure-title;

            ValueDisplay {
                active: root.active;
                model: root.pressure-model;
            }
        }
    }
}